name: Choose Env Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"
